# Generated by Django 3.2.6 on 2021-10-24 08:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_geofeature_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofeature',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
