# Generated by Django 3.2.6 on 2021-10-24 10:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_geofeature_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geofeature',
            name='features',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='point',
        ),
        migrations.AddField(
            model_name='geofeature',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
